name: CI/CD Pipeline


on: [push, pull_request]


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - run: pip install pytest pandas
            - run: pytest


    validate:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - run: pip install pandas
            - run: python test_data_validation.py


    train:
        runs-on: ubuntu-latest
        needs: validate
        steps:
            - uses: actions/checkout@v2
            - run: pip install pandas scikit-learn
            - run: python train.py


    deploy:
        runs-on: ubuntu-latest
        needs: train
        steps:
            - run: echo "🚀 Simulated deployment completed!"